### ISSUE TITLE
Tabs in Block Comments

### ISSUE THREAD

**Issue by jussij** [dlang-community/dfmt#115]
Using the version 2.0 of dfmt.

Given this code where the indenting is using spaces:

```
{
    /**
      * Params:
      */
    int main(string[] args)
    {
    }
}
```

Running dfmt with the tab option will change most of the lines to uses tabs instead of white space, but I think it gets these two lines wrong as they retain their leading white space indent:

```
<tab>   /**
<space>  * Params:
<space>  */
```

Those lines will certainly format incorrectly if the tab size is then changed.

**Comment by Hackerpilot** [comment]
I've been avoiding modifying comments because of the numerous ways that they can be screwed up.
