### ISSUE TITLE
version (Blah) statements

### ISSUE THREAD

**Issue by schancel** [dlang-community/dfmt#134]
dfmt currently eats spaces inappropriately after version() statements.

``` Diff
-    version (Posix) command ~= " 2> /dev/null 1> /dev/null";
-
+    version (Posix)command ~= " 2> /dev/null 1> /dev/null";
```

**Comment by Hackerpilot** [comment]
I'm seeing something different.

Input:
```d
version (Posix) command ~= " 2> /dev/null 1> /dev/null";

unittest
{
	version (Posix) command ~= " 2> /dev/null 1> /dev/null";
}
```

Output:
```d
version (Posix) command ~= " 2> /dev/null 1> /dev/null";

unittest
{
	version (Posix)
		command ~= " 2> /dev/null 1> /dev/null";
}
```
The second one is different because the parser doesn't accept the first one.

**Comment by schancel** [comment]
Strange.. It was from this source file (for more context) https://github.com/deadalnix/SDC/blob/master/tests/runner.d#L135

**Comment by qznc** [comment]
> The second one is different because the parser doesn't accept the first one.

Removing the first one does not change the formatting of the second one.

For clarification, dfmt should output the input unchanged?

**Comment by schancel** [comment]
@qznc Not necessarily unchanged, but it shouldn't eat the space after `version (Posix)`

**Comment by schancel** [comment]
Maybe this is no longer an issue.  I'll try again with a newer version.
