### ISSUE TITLE
How to build on Windows? *EDIT* Add DUB note to README

### ISSUE THREAD

**Issue by bruno-medeiros** [dlang-community/dfmt#234]
Is using `dub build` enough to build dfmt? 

I've used DUB on dfmt-0.4.5 and it seems to work fine, yet the README states one should use make to build dfmt (https://github.com/Hackerpilot/dfmt#building) , and, in the case of Windows there is also `build.bat` ? What's the story? I'm really hoping DUB is enough to build dfmt.

**Comment by Hackerpilot** [comment]
The idea is that on Windows you can choose between the batch file or Dub, and on other operating systems you can use the makefile or Dub.

**Comment by Hackerpilot** [comment]
The README doesn't mention Dub because I forgot to update it after adding Dub support.

**Comment by bruno-medeiros** [comment]
Don't add it to the documentation _after_, add it _during_. :sunglasses:  That is, update documentation on the same commit as the new functionality that is being introduced. That's one of the big advantages of having the doc on the same repo as the source code. (One reason why all the documentation for my Github projects like DDT is in the Git repo, and not on the wiki. wiki is disabled in fact)
That said it's a hard habit to be consistent at, I still forget about it once in a while :sweat_smile:
