### ISSUE TITLE
undefined identifier '__fhnd_info' & undefined identifier 'FHND_TEXT' when compiled from dub on Windows

### ISSUE THREAD

**Issue by anthony-y** [dlang-community/dfmt#238]
main.d(122,35): Error: undefined identifier '__fhnd_info'
src\dfmt\main.d(122,53): Error: undefined identifier 'FHND_TEXT'
src\dfmt\main.d(23,9): Error: function D main no return exp; or assert(0); at end of function
dmd failed with exit code 1.

**Comment by WebFreak001** [comment]
can't reproduce anymore
