### ISSUE TITLE
ufcs chains / pipelines

### ISSUE THREAD

**Issue by John-Colvin** [dlang-community/dfmt#260]
Breaking this off from https://github.com/Hackerpilot/dfmt/issues/7 as it's only one part of that.

This pattern is really very common in D:

``` D
auto blah = myRange
        .myCleverAlgorithm!(a => a.animal)
        .filter!"a.isButterfly"
        .each!spewFromDvdDrive;
```

and dfmt really mangles this sort of thing. I don't really know what algorithmic rules could be created that would make this work, but it would be great if there was something that at least caught common cases (`dfmt off/on` is fine, but obviously if a lot of code isn't being automatically formatted then that sucks. Ends up with a tension between getting things auto-formatted but not wanting so much fine-grained `dfmt off/on` visual noise).

**Comment by Hackerpilot** [comment]
> I don't really know what algorithmic rules could be created that would make this work...

I haven't been able to figure this out either. One of the problems is that in D there's no way (at the usage site) to determine the difference between a call to a zero-argument method, a member access, and a single-argument UFCS function call.

**Comment by BBasile** [comment]
I propose to use a hashset filled with the most commonly used functions in pipelines (beginning with phobos identifiers for algorithms and ranges, and extended by the time and the PRs).

I don't see any other solution that would be more reliable.

**Comment by thaven** [comment]
> One of the problems is that in D there's no way (at the usage site) to determine the difference between a call to a zero-argument method, a member access, and a single-argument UFCS function call.

Does that semantic really make a difference? A basic heuristic could be to look at both the length of the chain (number of dot-separated elements) and the line length if unfolded. Another possibility would be to simply respect the line-breaking choices made by the code author within such a chain.

**Comment by stefan-koch-sociomantic** [comment]
It's not that easy; for one it's hard to extract the users newline decisions as dfmt discards it while parsing; and the heuristics are rather complected, that said; I am going to working on this in the near future.

**Comment by BBasile** [comment]
A part of the solution would be in a first time to detect what looks like an UFCS chain an skip formatting of unaries / primaries. Detecting chains involve lookups for `tok!"."` until the end of the current expression statement (`tok!";"`) and looking if the columns are identical.
