### ISSUE TITLE
Please, add the option to disable newlines removal.

### ISSUE THREAD

**Issue by georgy7** [dlang-community/dfmt#270]
Hi! I am propose the enhancement.

I am not always satisfied, how dfmt (or any other automatic formatter) formats code.
And - I think, it is the common practice in Java comunity - I add some additional newlines.
To fix it. So, the code looks clearer. For example:

    string query = "some text some text some text some text" ~
        "some text some text some text some text some text " ~
        "some text some text some " ~
        "some text";

But dfmt just does not considered with my newlines. It transforms the code into something like this.

    string query = "some text some text some text some text" ~
        "some text some text some text some text some text " ~
        "some text some text some " ~ "some text";

Or, for example (Maybe, it deserves a separate issue):

    auto var1 = something(1, 2) + something(3, 4) +
        something(5, 6) + something(7, 8);

But dfmt does not only ignores my newlines. It makes something abnormal with the small logically grouped things, like, these parentheses and function calls.

It transforms into something like that:

    auto var1 = something(1, 2) + something(3, 4) + something(
        5, 6) + something(7, 8);

or

    auto var1 = something(1, 2) + something(3, 4) + something(5,
        6) + something(7, 8);

I am writing from my memories. It is not exact dfmt output.

So, what I propouse is 
to add the option to forbid dfmt to concatenate initially separated lines.

**Comment by georgy7** [comment]
The first example is very related to SQL statements.

**Comment by georgy7** [comment]
To be clear: I mean newlines **inside of a block only**. It will not affect settings about the brace style.

**Comment by stefan-koch-sociomantic** [comment]
```
// dfmt off
unchanged code
// dfmt on
```

**Comment by WebFreak001** [comment]
boo thats a hack, it should either take into account the previous indentation or block indentation should improve (the weights right now are ridiculous)

**Comment by stefan-koch-sociomantic** [comment]
@WebFreak001 propose a scheme please and i'll consider it.

**Comment by georgy7** [comment]
@stefan-koch-sociomantic 

>dfmt off

This feature is unrelated to the issue.

**Comment by Hackerpilot** [comment]
> (the weights right now are ridiculous)
If it's so easy to improve on them, where is the pull request that does so?

**Comment by WebFreak001** [comment]
> If it's so easy to improve on them, where is the pull request that does so?

Well the first step would be writing all of them down (which requires some long term usage) with rules what should be more important. Doing that will probably also merge a lot of existing issues into one. After that a PR shouldn't be that difficult if you have a good test file you can test everything against. I will definitely write down everything that I see that looks unnatural from now on. Especially arrays are a pretty difficult field which right now are packed in a way that could easily get unreadable in some situations.

**Comment by WebFreak001** [comment]
fixed with #471 using `--keep_line_breaks true`
