### ISSUE TITLE
Current stable version?

### ISSUE THREAD

**Issue by ilovezfs** [dlang-community/dfmt#300]
Based on https://github.com/dlang-community/dfmt/releases and https://github.com/dlang-community/dfmt/releases/latest I cannot tell if 0.4.5 or 0.50 is the current stable version.

Which version should be in Homebrew's stable spec? Thanks!

**Comment by stefan-koch-sociomantic** [comment]
v0.5.0

**Comment by ilovezfs** [comment]
@stefan-koch-sociomantic thanks for clarifying that. Could someone please designate 0.5.0 as an explicit GitHub release to remove the ambiguity? Thanks!

**Comment by WebFreak001** [comment]
I made the tags proper releases now

**Comment by ilovezfs** [comment]
Perfect. Thank you!
