### ISSUE TITLE
Is the neptune branching modelling working out?

### ISSUE THREAD

**Issue by wilzbach** [dlang-community/dfmt#353]
I constantly keep bumping into questing which branch I have to target and which one is master, so maybe switching back to a `master` (and maybe `stable` branch) model would be better.
I know the Sociomantic people have developed tools around that, but the other contributors (including myself) don't use them. So I'm not sure if the added work buys us any significant advantage.

See also: https://github.com/dlang-community/dfmt/issues/320

**Comment by Hackerpilot** [comment]
The `v0.x.x` branch is `master`, right? (I actually don't even know and I created this project)

**Comment by Hackerpilot** [comment]
I'd read the `contributing.md` file, but we don't have one.

**Comment by wilzbach** [comment]
> The v0.x.x branch is master, right?

I think so, but so far I merged new stuff into 0.7.x :O

CC @leandro-lucarella-sociomantic who introduced the neptune branching model.

**Comment by stefan-koch-sociomantic** [comment]
y.x.x is master by default PR's should be rebased on top of that.
where y is the current major version.

**Comment by Hackerpilot** [comment]
Can those of you who have a process that you'd like the rest of us to follow write down that process in a `contributing.md` file?

**Comment by BBasile** [comment]
Actually after discussion on IRC it appears that y.x.x can be used just like master. Their tools is the only to touch the other branches (those with semver, not the PRs ones of course).

**Comment by leandro-lucarella-sociomantic** [comment]
> The v0.x.x branch is master, right? (I actually don't even know and I created this project)

Yes, it's the default branch, so all your PRs should default to be based on that one.

**Comment by leandro-lucarella-sociomantic** [comment]
> Can those of you who have a process that you'd like the rest of us to follow write down that process in a contributing.md file?

We definitely should do that. It should probably be just copy&pasting this document: https://github.com/sociomantic-tsunami/neptune/blob/master/doc/library-contributor.rst

Please have a look at it and let us know if something is unclear so we can improve it.

@stefan-koch-sociomantic can take on this one? Maybe you can do a PR with copy&paste of that document in the `CONTRIBUTING.md` so people can ask for clarifications in the PR itself.

**Comment by stefan-koch-sociomantic** [comment]
@leandro-lucarella-sociomantic I am on it.

**Comment by stefan-koch-sociomantic** [comment]
WIP-PR: https://github.com/dlang-community/dfmt/pull/356

**Comment by wilzbach** [comment]
Urgh, so I just saw that the 0.8.0 release didn't have the binaries attached even though we have merged the scripts a while ago - the 0.7.0 release had them.

Apparently I know need to make two PRs to the repective v.0.8.x and v0.x.x branches(  https://github.com/dlang-community/dfmt/pull/358, https://github.com/dlang-community/dfmt/pull/359).

Considering that this repo has <10 PRs a month and is really low activity, I really don't like wasting so much time on this.
Can't we revert back to simply using `master` or maybe if really necessary `master` and `stable`?

**Comment by stefan-koch-sociomantic** [comment]
@wilzbach we use neptune versioning mainly to be able to use `neptune-release` which greatly simplifies our internal processes.

However I am also aware that it adds some friction when a non-sociomantic-member wants to do releases.

**Comment by leandro-lucarella-sociomantic** [comment]
> Apparently I know need to make two PRs to the repective v.0.8.x and v0.x.x branches( #358, #359).

No, you just need to make a PR against one branch. If it's a bug fix, to the oldest maintained patch branch that has that bug. If it's a new feature, to the oldest maintained minor branch where the feature can fit (if it's a new feature on top of another new feature that wasn't present in the oldest minor, then in the oldest minor where the feature can be implemented). https://github.com/sociomantic-tsunami/neptune/blob/master/doc/library-contributor.rst#submitting-pull-requests

The new features/bug fixes are propagated to newer branches as part of the release process by the library maintainer, not the contributors. And as @stefan-koch-sociomantic said, the `neptune-release` tools takes care of all the chores.

**Comment by wilzbach** [comment]
Sorry, but I don't think it worked:
- https://github.com/dlang-community/dfmt/blob/v0.x.x/.travis.yml
- https://github.com/dlang-community/dfmt/blob/v0.8.x/.travis.yml

**Comment by leandro-lucarella-sociomantic** [comment]
As I said in https://github.com/dlang-community/dfmt/pull/358#issuecomment-395820470, the problem was that your fixes were never released in v0.7.x. Now I released v0.7.1 with your fixes and that was propagated to v0.8.x (and released as v0.8.1) and v0.x.x.

All should be good now :)

**Comment by BBasile** [comment]
Neptune didn't work. We will go back to a single branch called `master`.
