### ISSUE TITLE
Update to dparse 0.9.6

### ISSUE THREAD

**Issue by BBasile** [dlang-community/dfmt#375]
Unfortunately with the FE 2.082 and the previous still not supported, the work to do has accumulated.

- expression-based contracts. (2.081)
- UDA for functions parameters. (2.082)
- enum member attributes. (2.082)

**Comment by LaurentTreguier** [comment]
I was just looking into expression-based contracts.

**Comment by BBasile** [comment]
If you want latest DCD in DLS i believe that 0.9.6 is necessary. There was an important fix related to scopes. (DCD requires >= 0.9.6 < 0.10.0)

**Comment by LaurentTreguier** [comment]
Yep, I can't upgrade DCD or D-Scanner until DFMT also uses libdparse 0.9.x

**Comment by BBasile** [comment]
done, even 0.9.8 now
