### ISSUE TITLE
Release of the binaries via TravisCI is broken due to a failure in the first step

### ISSUE THREAD

**Issue by BBasile** [dlang-community/dfmt#406]
[See log](https://travis-ci.org/dlang-community/dfmt/jobs/447075761#L640).
For now binaries can still be build but only after relaunching the remaining jobs manually.

**Comment by wilzbach** [comment]
This is some stuff from sociomantic. I suggest commenting the relevant parts.

**Comment by WebFreak001** [comment]
I forgot about this when I just wanted to release a new minor dfmt version to be compatible with the libdparse minor update, can we get Basile's commit in?
