### ISSUE TITLE
`dub run dfmt` keeps building dfmt anew each time.

### ISSUE THREAD

**Issue by veelo** [dlang-community/dfmt#407]
Something has regressed between version 0.8.2 and 0.8.3, which invalidates dub's cache it seems. Upon every invocation of `dub run dfmt -- mysource.d`, dub decides to rebuild dfmt anew, adding a good 10 seconds to every run. This makes it practically unusable in my case.

Probably a `preGenerateCommands` or `preBuildCommands` was added somewhere?

**Comment by veelo** [comment]
Indeed, reverting #379 fixes this problem. I can submit a PR for this, but I can imagine a real solution is preferable. Can anyone see one?

**Comment by BBasile** [comment]
No easy solution in mind. One would be that DUB generates the version file on demand or maybe if it set a compiler version automatically.

**Comment by BBasile** [comment]
by compiler version i mean just like for dmd -version=...

**Comment by BBasile** [comment]
well no this wouldn't work, it's not like an env variable.

**Comment by BBasile** [comment]
Other idea: dfmt as a library then. just like dcd and dscanner. you could write your own driver.

**Comment by veelo** [comment]
> Other idea: dfmt as a library then. just like dcd and dscanner. you could write your own driver.

But would that help at all? Wouldn’t it still rebuild that dependency?

**Comment by LaurentTreguier** [comment]
Yep, that's what it does

**Comment by veelo** [comment]
Should `dub run` invoke `preGenerateCommands` or `preBuildCommands` at all? I am thinking it should not...

**Comment by veelo** [comment]
> Since dub can't know if they will change anything compared to the previous build, it can only re-e execute them and rebuild the binary to be sure it's up to date.

Yeah I don't think it should do that, I just need to run the executable. I don't care whether it is the absolute newest or not. You don't expect your Debian system to check whether it can upgrade core-utils whenever you type `ls` either, that would be unworkable.

**Comment by LaurentTreguier** [comment]
I guess it was just to make it easy and allow skipping the `build` command. I agree that maybe it should only run `dub build` it if it can't find the binary, and just run it otherwise.
It's pretty ironic that besides doing that, dub doesn't even necessarily select the newest version of a package when running `dub build` or `dub run`, so it can be re-building an outdated version over and over again.
