### ISSUE TITLE
Space after in, out and invariant

### ISSUE THREAD

**Issue by belka-ew** [dlang-community/dfmt#448]
According to the [D Style](https://dlang.org/dstyle.html#phobos_declarations) there should be a space after `in`, `out` and `invariant` in contracts.

```diff
< in (value % 7 == 0)
< out (result; result % 11 == 0)
---
> in(value % 7 == 0)
> out(result; result % 11 == 0)
```

**Comment by WebFreak001** [comment]
this should probably be controlled by `dfmt_space_after_keywords` (default true) which still needs to be implemented, but seems to currently be an inconsistent default
