### ISSUE TITLE
Don't put template constraints on the same line as declaration

### ISSUE THREAD

**Issue by belka-ew** [dlang-community/dfmt#449]
[D Style](https://dlang.org/dstyle.html#phobos_declarations):

> Constraints on declarations should have the same indentation level as their declaration:

Even if it doesn't imply that the constraints should be on their own line, correctly intended constraints shouldn't be moved.

```diff
< void foo(R)(R r)
< if (R == 1);
---
> void foo(R)(R r) if (R == 1);
```

**Comment by WebFreak001** [comment]
optionally changable in your config as of #217 #215
