### ISSUE TITLE
Is it possible to have newlines after comma in function calls and array initialization

### ISSUE THREAD

**Issue by abhijat** [dlang-community/dfmt#463]
For example if I have a statement like:

```
auto sizes = [
    1, 
    2, 
    3, 
    4, 
    5
];
```

It is formatted to look like:
`auto sizes = [1, 2, 3, 4, 5];`

Is it possible to configure it to be formatted such that there is a newline after the comma as in the original snippet, without turning off dfmt for that expression?

I am using dfmt version 0.11.0

Thanks

**Comment by WebFreak001** [comment]
fixed with #471 using `--keep_line_breaks true`
