### ISSUE TITLE
hashmap with symbols not recognized/indented wrongly

### ISSUE THREAD

**Issue by FeepingCreature** [dlang-community/dfmt#485]
Consider the following code:
```
void main()
{
    int a;
    int[int] hashmap = [a : a, a : a, a : a];
}
```
Valid, and DMD accepts it. However, dfmt turns it into the very strange:
```
void main()
{
    int a;
    int[int] hashmap = [a : a, a:
        a, a:
        a];
}
```

Note that the first key-value has the correct spacing, but the others don't. Does it think it's doing labels?

**Comment by belka-ew** [comment]
Same as #462.

**Comment by WebFreak001** [comment]
#462 is caused by being in a delegate of that specific size I believe
