### ISSUE TITLE
Check argument

### ISSUE THREAD

**Issue by andre2007** [dlang-community/dfmt#510]
Scenario: In a CI test pipeline I want to check whether the D source code files are properly formatted. Therefore I want to check whether the output of `dfmt sample.d` corresponds with the actual content of `sample.d`.

This would be easy if dfmt would support a `--check` argument. There `dfmt sample.d --check` reads the content of file `sample.d` formats the source code and compares the formatted code with the actual file content. In case the content is equal, return code would be 0. Otherwise return code is unequal 0 and a diff like output shows the differences.

(Adding the diff could also be a second step later)

**Comment by Hackerpilot** [comment]
Just run `diff file.d <(dfmt file.d)`?

**Comment by Hackerpilot** [comment]
I think this is a duplicate of https://github.com/dlang-community/dfmt/issues/214

**Comment by andre2007** [comment]
@Hackerpilot 
yes you are right. Closing as a duplicate.
