### ISSUE TITLE
Dfmt(version 0.15.0 from Arch) seems to be eating characters.

### ISSUE THREAD

**Issue by abenedic** [dlang-community/dfmt#583]
I am very sorry if this is already a known issue, I am using version 0.15.0 from the Arch Linux repositories.

Using a file like 
```
import document;

void doit(string file_name)
{
    Document[] t = read_jsonl(file_name);

}

int main(string[] args)
{
    if (args.length > 2)
    {
        return 1;
    }
    doit(args[1]);

    return 0;
}
```
I am getting output like:
```
03:28:31 alex@Comp src ±|main ✗|→ dfmt main.d
main.d(13:15)[error]: Expected `;` instead of `1`
import ocument;

void doit(string file_name)
{
    Document[] t = read_jsonl(file_name);

}

int main(string[] args)
{
    if (args.length > 2)
    {
        eturn 1;
    }
    doit(args[1]);

    return 0;
}
```
Which is missing the `d` in document and `r` in return.
```
03:29:09 alex@Comp src ±|main ✗|→ dfmt --version
v0.15.0
```
This is cut down quite a bit from the original version that triggered the bug, but still compiles fine using ldc.

**Comment by WebFreak001** [comment]
can't reproduce, can you upload the exact source file? there may be UTF BOM or something similar

**Comment by WebFreak001** [comment]
ah, huh with the arch version I can indeed reproduce (on the return) - not sure what's going on here and how they build it

**Comment by WebFreak001** [comment]
there seems to be an issue in the inline assembly / SIMD code branch that for some reason only occurs using the makefile compiled binary with LDC (dub LDC binary works)
